"""
Citation Builder

Creates citation references from retrieved chunk metadata.
Citations are generated by the application rather than the LLM,
which prevents the model from inventing source information.
"""


class CitationBuilder:
    """Builds source citations from retrieved chunks."""

    @staticmethod
    def build(results: list[dict]) -> list[dict]:
        """
        Create unique citations from retrieved results.

        Args:
            results: Re-ranked retrieval results.

        Returns:
            List of citation dictionaries.
        """

        citations = []
        seen = set()

        for result in results:

            chunk = result["chunk"]
            metadata = chunk.metadata

            filename = metadata.get(
                "filename",
                "Unknown source",
            )

            page = metadata.get("page")

            # Use filename + page to avoid duplicate citations.
            citation_key = (filename, page)

            if citation_key in seen:
                continue

            seen.add(citation_key)

            citation = {
                "id": len(citations) + 1,
                "filename": filename,
                "page": page,
                "chunk_index": metadata.get(
                    "chunk_index"
                ),
            }

            citations.append(citation)

        return citations