name: RAGForge CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:

  test:

    name: Tests

    runs-on: ubuntu-latest

    steps:

      # ------------------------------------------
      # Checkout repository
      # ------------------------------------------

      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------------------------------
      # Setup Python
      # ------------------------------------------

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # ------------------------------------------
      # Install dependencies
      # ------------------------------------------

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ------------------------------------------
      # Run unit tests
      # ------------------------------------------

      - name: Run tests
        run: |
          pytest -q